### ISSUE TITLE
Exercise 7 (Load External Content JS - 7.1)

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/jqfundamentals#4]
**Load External Content**

Open the file /exercises/index.html in your browser. Use the file /exercises/js/load.js. Your task is to load the content of a blog item when a user clicks on the title of the item.
1. Create a target div after the headline for each blog post and store a reference to it on the headline element using `$.fn.data`.
2. Bind a click event to the headline that will use the `$.fn.load` method to load the appropriate content from /exercises/data/blog.html into the target div. Don't forget to prevent the default action of the click event.

**Note that each blog headline in index.html includes a link to the post. You'll need to leverage the href of that link to get the proper content from blog.html. Once you have the href, here's one way to process it into an ID that you can use as a selector in `$.fn.load`:**

`var href = 'blog.html#post1';`
`var tempArray = href.split('#');`
`var id = '#' + tempArray[1];`

Remember to make liberal use of `console.log` to make sure you're on the right path!

https://github.com/ayodeleDD/jqfundamentals/blob/master/exercises/exercise7/load.js

**Comment by segunadeleye** [comment]
Let's have `init()` set the stage and another method handle the loading of content.

**Comment by ayodeleopetumo** [comment]
Done

**Comment by segunadeleye** [comment]
Looks good
