### ISSUE TITLE
.delegate / .on() Exercise

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/jqfundamentals#7]
Create a stack of divs. Initially an empty container should display a button on right side says "add item", should add a div to the stack with an incremental number(starting from 1) clicking any item in the stack should highlight that item clickingthe last item on the stack should remove that item from the stackhint: use jQuery delegate. live method has been removed from the latest version of jQuery so you may want to use on() or delegate()

https://github.com/ayodeleDD/jqfundamentals/blob/master/exercises/exercise8/stack.js

**Comment by segunadeleye** [comment]
Okay cool...just some changes...
Move all events handler into a method and make the each event make a call to the respective method just like you did for `addStackedDiv()`

Also, `const self = this`, where is this used?

**Comment by ayodeleopetumo** [comment]
code optimised

**Comment by segunadeleye** [comment]
Good one
